/**
 * Antigravity Cockpit - Model ID Constants
 * Centralized definition of all model IDs used in the extension.
 */

// Gemini Models
export const MODEL_GEMINI_3_PRO_LOW = 'MODEL_PLACEHOLDER_M7';
export const MODEL_GEMINI_3_PRO_HIGH = 'MODEL_PLACEHOLDER_M8';
export const MODEL_GEMINI_3_1_PRO_LOW = 'MODEL_PLACEHOLDER_M36';
export const MODEL_GEMINI_3_1_PRO_HIGH = 'MODEL_PLACEHOLDER_M37';
export const MODEL_GEMINI_3_FLASH = 'MODEL_PLACEHOLDER_M18';
export const MODEL_GEMINI_3_PRO_IMAGE = 'MODEL_PLACEHOLDER_M9';

// Claude Models
export const MODEL_CLAUDE_4_5_SONNET = 'MODEL_CLAUDE_4_5_SONNET';
export const MODEL_CLAUDE_4_5_SONNET_THINKING = 'MODEL_CLAUDE_4_5_SONNET_THINKING';
export const MODEL_CLAUDE_SONNET_4_6_THINKING = 'MODEL_PLACEHOLDER_M35';
export const MODEL_CLAUDE_OPUS_4_5_THINKING = 'MODEL_PLACEHOLDER_M12';
export const MODEL_CLAUDE_OPUS_4_6_THINKING = 'MODEL_PLACEHOLDER_M26';

// Other Models
export const MODEL_OPENAI_GPT_OSS_120B_MEDIUM = 'MODEL_OPENAI_GPT_OSS_120B_MEDIUM';

// Blacklisted Models
export const MODEL_CHAT_20706 = 'MODEL_CHAT_23310'; // Note: Potential inconsistency in original recommended_models.ts, check later
export const MODEL_CHAT_23310 = 'MODEL_CHAT_23310';
export const MODEL_GOOGLE_GEMINI_2_5_FLASH = 'MODEL_GOOGLE_GEMINI_2_5_FLASH';
export const MODEL_GOOGLE_GEMINI_2_5_FLASH_THINKING = 'MODEL_GOOGLE_GEMINI_2_5_FLASH_THINKING';
export const MODEL_GOOGLE_GEMINI_2_5_FLASH_LITE = 'MODEL_GOOGLE_GEMINI_2_5_FLASH_LITE';
export const MODEL_GOOGLE_GEMINI_2_5_PRO = 'MODEL_GOOGLE_GEMINI_2_5_PRO';
export const MODEL_PLACEHOLDER_M19 = 'MODEL_PLACEHOLDER_M19';
